<?php

namespace POP\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceRepository extends EntityRepository
{
}
