pop_admin_agence:
    resource: "@POPAdminBundle/Resources/config/routing/agence.yml"
    prefix:   /agence

pop_admin_quartier:
    resource: "@POPAdminBundle/Resources/config/routing/quartier.yml"
    prefix:   /quartier

pop_admin_ville:
    resource: "@POPAdminBundle/Resources/config/routing/ville.yml"
    prefix:   /ville

pop_admin_region:
    resource: "@POPAdminBundle/Resources/config/routing/region.yml"
    prefix:   /region

pop_admin_pays:
    resource: "@POPAdminBundle/Resources/config/routing/pays.yml"
    prefix:   /pays

pop_admin_homepage:
    path:     /
    defaults: { _controller: POPAdminBundle:Default:index }
